export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_REPOSITORY_NAME = 'CHANGE_REPOSITORY_NAME';
export const MERGE_DATA_INSIGHTS = 'MERGE_DATA_INSIGHTS';
export const PULL_REQUEST_DATA_INSIGHTS = 'PULL_REQUEST_DATA_INSIGHTS';